# Site settings
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ .Site.Params.myvariable }}.
baseurl = "/" # The subpath of your site, e.g. / or /blog
languageCode = "en-us"
languageLang = "en"
title = "My New Hugo Site"

[[params]]
  description = '''
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your RSS feed description.
  '''
  author = "Your name"

# Build settings

# Enable this to have links relativized by Hugo
# E.g,  if your /post/first/ page contains a link 
# to /about/, Hugo will rewrite the URL to ../../about/
relativeURLs = false

# Enable to have links open in new tab
hrefTargetBlank = false

# Categories and tags disabled for an easier start
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["taxonomy", "taxonomyTerm"]
